blog/urls.py
#!/usr/bin/env python
# _*_ coding: utf-8 _*_

from django.conf.urls import url

from blog import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<category_id>\d+)$', views.CategoryView.as_view(),
        name='category'),
    url(r'tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^article/(?P<article_id>\d+)/comment/$',
        views.CommentPostView.as_view(), name='comment'),
]

blog_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

blog/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.urlresolvers import reverse

from collections import defaultdict

from datetime import datetime


class BlogComment(models.Model):
    user_name = models.CharField('评论者昵称', max_length=100)
    user_email = models.EmailField('评论者邮箱', max_length=255)
    body = models.TextField('评论内容')
    created_time = models.DateTimeField('评论发表时间', auto_now_add=True)
    article = models.ForeignKey('Article', verbose_name='评论所属文章',
                                     on_delete=models.CASCADE)


class ArticleManager(models.Manager):
    
    def archive(self):
        date_list = Article.objects.datetimes('created_time', 'month',
                                             order='DESC')
        date_dict = defaultdict(list)
        for dt in date_list:
            date_dict[dt.year].append(dt.month)
        return date_dict


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )

    title = models.CharField(u'标题', max_length=70)
    body = models.TextField(u'正文')
    created_time = models.DateTimeField(u'创建时间',)
    last_modified_time = models.DateTimeField(u'修改时间', auto_now=True)
    status = models.CharField(u'文章状态', max_length=1, choices=STATUS_CHOICES)
    abstract = models.CharField(u'摘要', max_length=54, blank=True, null=True,
                                help_text="可选，若为空则自动截取正文的前54个字符")
    views = models.PositiveIntegerField(u'浏览量', default=0)
    likes = models.PositiveIntegerField(u'点赞数', default=0)
    topped = models.BooleanField(u'置顶', default=False)
    category = models.ForeignKey('Category', verbose_name='分类',
                                 null=True,
                                 # 表示删除了某个foreignkey后，对应的文章的该值会被设置为NULL
                                 on_delete=models.SET_NULL)
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)

    objects = ArticleManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-last_modified_time']
        db_tablespace = "tables"
    # 方便获取文章url
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'article_id': self.pk})


class Category(models.Model):
    name = models.CharField(u'分类名', max_length=20)
    created_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField(u'修改时间', auto_now=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(u'标签名', max_length=20)
    created_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField(u'修改时间', auto_now=True)

    def __str__(self):
        return self.name

blog/forms.py
#!/usr/bin/env python
# _*_ coding: utf-8 _*_

from django import forms

from .models import Article, BlogComment


class BlogCommentForm(forms.ModelForm):
    class Meta:
        model = BlogComment
        fields = ['user_name', 'user_email', 'body']
        widget = {
            'user_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "请输入昵称",
                'aria-describedby': "sizing-addon1",
            }),
            'user_email': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "请输入邮箱",
                'aria-describedby': "sizing-addon1",
            }),
            'body': forms.Textarea(attrs={'placeholder': '我来评两句~'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.views.generic.edit import FormView

from .models import Article, Category, Tag
from .forms import BlogCommentForm

import markdown2

class IndexView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        article_list = Article.objects.filter(status='p')
        for article in article_list:
            article.body =markdown2.markdown(article.body,
                                             extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        kwargs['date_archive'] = Article.objects.archive()
        return super(IndexView, self).get_context_data(**kwargs)


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/detail.html'
    context_object_name = 'article'
    pk_url_kwarg = 'article_id'

    def get_object(self):
        obj = super(ArticleDetailView, self).get_object()
        obj.body = markdown2.markdown(obj.body, extras=['fenced-code-blocks'],)
        return obj

    def get_context_data(self, **kwargs):
        kwargs['comment_list'] = self.object.blogcomment_set.all()
        kwargs['form'] = BlogCommentForm()
        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryView(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        article_list = Article.objects.filter(category=self.kwargs['category_id'], status='p')
        for article in article_list:
            article.body = markdown2.markdown(article.body,
                                              extras=['fenced-code-blocks'])
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        return super(CategoryView, self).get_context_data(**kwargs)


class TagView(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        article_list = Article.objects.filter(tags=self.kwargs['tag_id'], status='p')
        for article in article_list:
            article.body = markdown2.markdown(article.body,
                                              extras=['fenced-code-blocks'])
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(TagView, self).get_context_data(**kwargs)


class CommentPostView(FormView):
    form_class = BlogCommentForm
    template_name = 'blog/detail.html'

    def form_valid(self, form):
        target_article = get_object_or_404(Article, pk=self.kwargs['article_id'])
        comment = form.save(commit=False)
        comment.article = target_article
        comment.save()

        self.success_url = target_article.get_absolute_url()
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form):
        target_article = get_object_or_404(Article, pk=self.kwargs['article_id'])
        return render(self.request, 'blog/detail.html', {
            'form': form,
            'article': target_article,
            'comment_list': target_article.blogcomment_set.all(),
        })

blog/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Myblog</title>
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pygments/github.css' %}">
    <link rel="stylesheet" href="{% static 'lib/css/bootstrap.min.css' %}">
</head>
<body>
<div id="header">
    <div id="header-warp">
        <a href="{% url 'blog:index' %}" title="第一个博客" id="logo"></a>
        <ul id="header-nav">
            <li><a href="{% url 'blog:index' %}">首页</a></li>
        </ul>
        <div id="header-right" class="login">
            <div id="user-info">
                <span id="dropdown-button">登录</span>
            </div>
        </div>
    </div>
</div>

{% block content %}{% endblock %}

<div id="footer" class="noselect">
    <ul id="ft-links">
        <li><a href="" target="_blank">友情链接1</a></li>
    </ul>
    <ul id="ft-about-links">
        <li><a href="" target="_blank">友情链接2</a></li>
    </ul>
    <div id="copyright">&copy; djangoBlog</div>
</div>
<script type="text/javascript" src="{% static 'blog/js/jquery.js' %}"></script>
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script type="text/javascript" src="{% static 'lib/js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/blog/comment.html
<div class="comment">
    <div class="comment-main">
        <p class="head">评论详情</p>
        <form method="post" action="{% url 'blog:comment' article.pk %}">
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
            </div>
            <button type="submit" class="com-button">评论</button>
        </form>
        <p class="comment-count">共{{ 0 }}条评论</p>
        <hr>
        {% for comment in comment_list %}
            <div class="main-content">
{#                <img src="月英1.jpg" class="user-avatar">#}
                <span class="user-nickname">{{ comment.user_name }}</span>
                <time class="time">{{ comment.created_time }}</time>
                <div class="comment-content">
                    {{ comment.body }}
                </div>
{#                <a href="">回复</a>#}
            </div>
            <hr>
        {% endfor %}
    </div>
</div>

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div id="bd" class="wrp clear-fix">
                <div id="main">
                    <div id="detail-title">
                        <ul id="single-nav">
                            <li><a href="{% url 'blog:index' %}">首页</a></li>
                            <li>&gt;</li>
                            <li>
                                <ul class="post-categories">
                                    <li><a href="" title=""
                                           rel="category">{{ article.category.name }}</a>
                                    </li>
                                </ul>
                            </li>
                            <li>&gt;</li>
                            <li class="title-active"><a href="{% url 'blog:detail' article.pk %}"
                                                        rel="bookmark">{{ article.title }}</a>
                            </li>
                        </ul>
                    </div>
                    <div id="post-1951"
                         class="post-1951 post type-post status-publish format-standard hentry category-meida-report">
                        <div class="post-hd">
                            <h1 class="title">{{ article.title }}</h1>
                        </div>
                        <div class="date-read">
                            <i class="icon-date"></i><span
                                class="date">{{ article.last_modified_time|date:"Y年n月d日" }}</span>
                        </div>
                        <div class="post-bd">
                            {{ article.body |safe }}
                        </div>
                    </div>
                </div>
            </div>
            {% include 'blog/comment.html' %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
    <div id="banner" class="noselect"></div>

    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div id="category" class="noselect">
                    <div id="category-title">
                        <ul>
                            <li>分类：</li>
                            {% for category in category_list %}
                                <li class="cat-item"><a
                                        href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div id="bd" class="wrp clear-fix">
                    <div id="main">
                        {% load paginate_tags %}
                        {% paginate article_list 2 %}
                        {% for article in article_list %}
                            <div class="post">
                                <div class="post-hd">
                                    <h1 class="title"><a
                                            href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a></h1>
                                </div>
                                <div class="post-bd">
                                    <!-- 	<p><a href=""><img src="" alt=""></a></p> -->
                                    <p>{{ article.abstract }}</p>
                                    <p><a href="" class="more-link"></a></p>
                                </div>
                                <div class="post-ft">
                                    <a href="{% url 'blog:detail' article.id %}" class="more">阅读全文>></a>
                                    <i class="icon-date"></i>
                                    <span class="date">{{ article.last_modified_time|date:"Y年n月d日" }}</span>
                                </div>
                            </div>
                        {% endfor %}
                        {% include 'blog/pagination.html' %}
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <!-- tags -->
                <h3>标签:</h3>
                <div class="list-group">
                    {% for tag in tag_list %}
                        <a href="{% url 'blog:tag' tag.pk %}" class="list-group-item"><span
                                class="badge"></span>{{ tag.name }}</a>
                    {% endfor %}
                </div>

                <!-- archive -->
                <h3>文章归档：</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% for year,months in date_archive %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ forloop.counter }}"
                                       aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                        {{ year }} 年
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="heading{{ forloop.counter }}">
                                <div class="panel-body">
                                    {% for month in months %}
                                        <a href="{% url 'blog:archive' year month %}"><p>{{ month }} 月</p></a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/pagination.html
<div id="pagenavi" class="noselect">
    {% if article_list.has_previous %}
        <a class="previous-page" href="?page={{ article_list.previous_page_number }}">
            <span class="icon-previous"></span>上一页
        </a>
    {% endif %}

    {% if first_page == current_page %}
        <span class="first-page current">1</span>
    {% else %}
        <a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %}
        <span>...</span>
    {% endif %}

    {% for page in pages %}
        {% if page == current_page %}
            <span class="current">{{ page }}</span>
        {% else %}
            <a href="?page={{ page }}">{{ page }}</a>
        {% endif %}
    {% endfor %}

    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <span class="current">{{ last_page }}</span>
        {% else %}
            <a href="?page={{ last_page }}">{{ last_page }}</a>
        {% endif %}
    {% endif %}

    {% if article_list.has_next %}
        <a class="next-page" href="?page={{ article_list.next_page_number }}">
            下一页<span class="icon-next"></span>
        </a>
    {% endif %}
</div>